sudo: required
git:
  submodules: false
language: java
jdk:
  - openjdk8
env:
  - NODE_VERSION="16"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_install:
  - 'pyenv install 3.6.15'
  - 'pyenv global 3.6.15'
  - 'nvm install $NODE_VERSION'
install: npm install