name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The new version to tag and release'
        default: ''
        required: true
        type: string

jobs:
  update-version:
    name: Update package version
    runs-on: ubuntu-latest
    steps:
      - name: 
        run: npx json -I -f package.json -e 'this.version="${{ inputs.version }}"'